/**
 * 组件样式生成器
 *
 * 为以下元素生成主题相关的样式：
 * - 引用（blockquote / multiquote-*）
 * - 链接（a）
 * - 加粗/斜体/删除线/下划线/高亮（strong / em / del / u / mark）
 * - 分隔线（hr）
 * - 代码（pre code / inline code）
 * - 图片/图注（img / figcaption）
 * - 表格（table / th / td）
 * - 脚注（footnote-*）
 *
 * 所有样式通过 var(--wemd-*) 引用主题 Token。
 */
import type { DesignTokens } from "../theme-schema/types";

export function renderComponentCss(_tokens: DesignTokens): string {
  return [
    `/* === 引用 === */`,
    `#wemd .multiquote-1 {`,
    `  border-left: 4px solid var(--wemd-primary);`,
    `  background: var(--wemd-bg-soft);`,
    `  color: var(--wemd-text-soft);`,
    `  border-radius: var(--wemd-border-radius);`,
    `}`,
    `#wemd .multiquote-1 p {`,
    `  font-size: 15px;`,
    `  color: var(--wemd-text-soft);`,
    `  line-height: var(--wemd-line-height);`,
    `}`,
    `#wemd .multiquote-2 {`,
    `  border-left: 3px solid var(--wemd-primary-dark);`,
    `  background: var(--wemd-bg-muted);`,
    `  border-radius: var(--wemd-border-radius);`,
    `}`,
    `#wemd .multiquote-2 p {`,
    `  font-size: 15px;`,
    `  color: var(--wemd-text-soft);`,
    `  line-height: 1.7;`,
    `}`,
    `#wemd .multiquote-3 {`,
    `  border-left: 2px solid var(--wemd-primary);`,
    `  background: var(--wemd-bg-muted);`,
    `  border-radius: var(--wemd-border-radius);`,
    `}`,
    `#wemd .multiquote-3 p {`,
    `  font-size: 14px;`,
    `  color: var(--wemd-text-soft);`,
    `}`,

    `/* === 链接 === */`,
    `#wemd a {`,
    `  color: var(--wemd-primary);`,
    `  text-decoration: none;`,
    `  border-bottom: 1px solid var(--wemd-primary);`,
    `  font-weight: 500;`,
    `}`,

    `/* === 文本修饰 === */`,
    `#wemd strong {`,
    `  font-weight: 600;`,
    `  color: var(--wemd-primary);`,
    `}`,
    `#wemd em {`,
    `  font-style: italic;`,
    `  color: var(--wemd-primary);`,
    `  font-weight: 500;`,
    `}`,
    `#wemd em strong {`,
    `  font-weight: 700;`,
    `  font-style: italic;`,
    `  color: var(--wemd-primary-dark);`,
    `}`,
    `#wemd del {`,
    `  text-decoration: line-through;`,
    `  color: var(--wemd-text-soft);`,
    `  opacity: 0.7;`,
    `}`,
    `#wemd u {`,
    `  text-decoration: underline;`,
    `  text-underline-offset: 0.18em;`,
    `  text-decoration-thickness: 1px;`,
    `}`,
    `#wemd mark {`,
    `  background: linear-gradient(135deg, #fff9c4, #fff59d);`,
    `  color: var(--wemd-text-strong);`,
    `  padding: 2px 4px;`,
    `  border-radius: 3px;`,
    `  font-weight: 500;`,
    `}`,

    `/* === 分隔线 === */`,
    `#wemd hr {`,
    `  border: none;`,
    `  height: 1px;`,
    `  background: var(--wemd-border);`,
    `  margin: 28px 0;`,
    `}`,

    `/* === 行内代码 === */`,
    `#wemd p code, #wemd li code {`,
    `  background: var(--wemd-primary-light);`,
    `  padding: 3px 6px;`,
    `  border-radius: 3px;`,
    `  color: var(--wemd-primary-dark);`,
    `  font-family: "SF Mono", Monaco, "Cascadia Code", "Roboto Mono", Consolas, monospace;`,
    `  font-size: 0.9em;`,
    `  margin: 0 3px;`,
    `  border: 1px solid var(--wemd-primary-light);`,
    `}`,

    `/* === 代码块 === */`,
    `#wemd pre code {`,
    `  background: var(--wemd-bg-soft);`,
    `  padding: 16px;`,
    `  border-radius: var(--wemd-border-radius);`,
    `  overflow-x: auto;`,
    `  font-size: 14px;`,
    `  line-height: 1.6;`,
    `  color: var(--wemd-text-normal);`,
    `  border: 1px solid var(--wemd-border);`,
    `}`,

    `/* === 图片/图注 === */`,
    `#wemd img {`,
    `  margin: 24px auto;`,
    `  border-radius: var(--wemd-border-radius);`,
    `}`,
    `#wemd figcaption {`,
    `  text-align: center;`,
    `  font-size: 14px;`,
    `  color: var(--wemd-text-soft);`,
    `  margin-top: 8px;`,
    `}`,

    `/* === 表格 === */`,
    `#wemd table tr th, #wemd table tr td {`,
    `  border: 1px solid var(--wemd-border);`,
    `  padding: 10px 14px;`,
    `  font-size: 15px;`,
    `  color: var(--wemd-text-normal);`,
    `  line-height: 1.6;`,
    `}`,
    `#wemd table tr th {`,
    `  background: var(--wemd-primary-light);`,
    `  color: var(--wemd-primary-dark);`,
    `  font-weight: 600;`,
    `}`,
    `#wemd table tr:nth-child(2n) {`,
    `  background-color: var(--wemd-bg-soft);`,
    `}`,
    `#wemd table tr th:nth-of-type(n), #wemd table tr td:nth-of-type(n) {`,
    `  min-width: 100px;`,
    `}`,

    `/* === 脚注 === */`,
    `#wemd .footnote-word {`,
    `  color: var(--wemd-primary);`,
    `  font-weight: 500;`,
    `  border-bottom: 1px dashed var(--wemd-primary);`,
    `}`,
    `#wemd .footnote-ref {`,
    `  color: var(--wemd-primary);`,
    `  font-weight: 600;`,
    `}`,
    `#wemd .footnotes-sep:before {`,
    `  content: "参考资料";`,
    `  font-weight: 600;`,
    `  margin-top: 36px;`,
    `  margin-bottom: 16px;`,
    `  display: block;`,
    `  font-size: 18px;`,
    `  color: var(--wemd-text-strong);`,
    `}`,
    `#wemd .footnote-num {`,
    `  display: inline-block;`,
    `  width: 24px;`,
    `  text-align: right;`,
    `  margin-right: 8px;`,
    `  color: var(--wemd-text-soft);`,
    `  font-weight: 500;`,
    `}`,
    `#wemd .footnote-item p {`,
    `  display: inline;`,
    `  font-size: 14px;`,
    `  color: var(--wemd-text-soft);`,
    `  line-height: 1.8;`,
    `}`,
    `#wemd .footnote-item p em {`,
    `  font-style: normal;`,
    `  color: var(--wemd-text-soft);`,
    `  margin-left: 6px;`,
    `}`,

    `/* === 公式 === */`,
    `#wemd .block-equation > svg {`,
    `  display: block;`,
    `  margin: 20px auto;`,
    `}`,
    `#wemd .inline-equation > svg {`,
    `  vertical-align: middle;`,
    `}`,
  ].join("\n");
}
