/**
 * 额外组件样式（Callout 提示块 / Imageflow / Mermaid）
 *
 * 这些是项目层面的功能组件，不跟随主题 Token 大幅变化。
 * 始终注入到最终 CSS。
 */
export function renderExtrasCss(): string {
  return [
    `/* === Callout 提示块 === */`,
    `#wemd .callout {`,
    `  margin: 28px 0;`,
    `  padding: 22px 24px;`,
    `  border-radius: 22px;`,
    `  border: 1px solid rgba(7, 193, 96, 0.15);`,
    `  background: var(--wemd-bg-card);`,
    `  box-shadow: 0 25px 45px rgba(15, 23, 42, 0.12);`,
    `  position: relative;`,
    `  overflow: hidden;`,
    `}`,
    `#wemd .callout::after {`,
    `  content: "";`,
    `  position: absolute;`,
    `  inset: 0;`,
    `  border-radius: 22px;`,
    `  pointer-events: none;`,
    `  background: linear-gradient(120deg, rgba(7,193,96,0.05), rgba(7,89,193,0.03));`,
    `}`,
    `#wemd .callout-title {`,
    `  display: flex;`,
    `  align-items: center;`,
    `  gap: 10px;`,
    `  font-weight: 600;`,
    `  margin-bottom: 12px;`,
    `  color: var(--wemd-text-strong);`,
    `  font-size: 16px;`,
    `  letter-spacing: 0.05em;`,
    `}`,
    `#wemd .callout-icon { margin-right: 8px; font-size: 20px; }`,

    `#wemd .callout-note {`,
    `  border-color: rgba(100, 116, 255, 0.25);`,
    `  background: linear-gradient(135deg, #f7f9ff, #edf2ff);`,
    `}`,
    `#wemd .callout-tip {`,
    `  border-color: rgba(139, 92, 246, 0.25);`,
    `  background: linear-gradient(135deg, #f5f3ff, #ede9fe);`,
    `}`,
    `#wemd .callout-important {`,
    `  border-color: rgba(14, 165, 233, 0.25);`,
    `  background: linear-gradient(135deg, #f0f9ff, #e0f2ff);`,
    `}`,
    `#wemd .callout-warning {`,
    `  border-color: rgba(249, 158, 0, 0.25);`,
    `  background: linear-gradient(135deg, #fff8ed, #fff3dc);`,
    `}`,
    `#wemd .callout-caution {`,
    `  border-color: rgba(239, 68, 68, 0.25);`,
    `  background: linear-gradient(135deg, #fff5f5, #ffe7e7);`,
    `}`,

    `/* === Mermaid 覆盖 === */`,
    `#wemd .mermaid .node rect,`,
    `#wemd .mermaid .node circle,`,
    `#wemd .mermaid .node ellipse,`,
    `#wemd .mermaid .node polygon {`,
    `  fill: var(--wemd-bg-card) !important;`,
    `  stroke: var(--wemd-primary) !important;`,
    `}`,
    `#wemd .mermaid .label {`,
    `  color: var(--wemd-text-normal) !important;`,
    `}`,

    `/* === 滚动图 === */`,
    `#wemd .imageflow-layer1 { margin-top: 1em; margin-bottom: 0.5em; border: 0; padding: 0; overflow: hidden; }`,
    `#wemd .imageflow-layer2 { white-space: nowrap; width: 100%; overflow-x: scroll; }`,
    `#wemd .imageflow-layer3 {`,
    `  display: inline-block; word-wrap: break-word; white-space: normal;`,
    `  vertical-align: top; width: 80%; margin-right: 10px; flex-shrink: 0;`,
    `}`,
    `#wemd .imageflow-img { display: block; width: 100%; height: auto; max-height: 300px; object-fit: contain; border-radius: 4px; }`,
    `#wemd .imageflow-caption { text-align: center; margin-top: 0; padding-top: 0; }`,
  ].join("\n");
}
